language: java
jdk:
  - oraclejdk8
  
services:
  - docker

before_install:
- docker pull jenkins
- docker run -d -p 8080:8080 -p 50000:50000 --name testJenkins --env JAVA_OPTS="-Dhudson.Main.development=true -Djenkins.install.runSetupWizard=false" jenkins
- docker ps -a
- docker exec -it testJenkins git clone https://github.com/tsu-denim/unjenkinsTestFiles.git /var/jenkins_home/jobs
- sleep 10
- curl -X POST http://localhost:8080/reload
- sleep 10
- rtn=$(curl http://localhost:8080/job/Test/api/json)
- echo $rtn

install: mvn -q clean verify

addons:
  sonarqube:
    token:
      secure: 4e991e3c9bd049aa16978d336dc56d0d99873f94

script:
- sonar-scanner

