language: java
jdk:
  - oraclejdk8
  
services:
  - docker

before_install:
- docker pull jenkins
- docker run -p 8080:8080 -p 50000:50000 --name testJenkins --env JAVA_OPTS="-Dhudson.Main.development=true -Djenkins.install.runSetupWizard=false" jenkins
- docker ps -a
- docker exec -it testJenkins git clone https://github.com/tsu-denim/unjenkins.git /var/jenkins_home/jobs
- docker restart testJenkins
