serverSettings:
  servicePort : 8080
  heartbeatInterval : 10000
  daemonInterval : 30000
  remoteHostDomainForHealthCheck : localhost
  remoteHostPortForHealthCheck : 8888
  sslKeyRepositoryPath : thePath
  sslKeyPassword : javakeys
  remoteJenkinsHostDomain : jenkins.inintca.com
  remoteJenkinsHostPort : 8443
  jenkinsUserName : kurt.waechter@inin.com
  jenkinsApiToken : 55079fb68d9018d7a57d0633161a415a
