serverSettings:
  servicePort : 8989
  heartbeatInterval : 10000
  remoteHostDomainForHealthCheck : localhost
  remoteHostPortForHealthCheck : 8888
  sslKeyRepositoryPath : thePath
  sslKeyPassword : javakeys
  remoteJenkinsHostDomain : kdzmkzjenkins.northcentralus.cloudapp.azure.com
  remoteJenkinsHostPort : 8080
  jenkinsUserName : webadmin
  jenkinsApiToken : 3a339eefb8927605c851e6d4aaa8755a
