serverSettings:
  servicePort : 8989
  heartbeatInterval : 10000
  remoteHostDomainForHealthCheck : localhost
  remoteHostPortForHealthCheck : 8888
  sslKeyRepositoryPath : thePath
  sslKeyPassword : javakeys
  remoteJenkinsHostDomain : localhost
  remoteJenkinsHostPort : 8080
  jenkinsUserName : kwaechter
  jenkinsApiToken : 4c69fca9d9459bdf941d8d72fa23926b
